### PR TITLE
add verbosity option to crepe.predict()

### PR DESCRIPTION
**Pull request by wooters**
Hello! 

Thank you for creating this package. It's a very cool project!

I'm not sure if you are accepting pull-requests, but I wanted to be able to run the `predict()` function such that it wouldn't print the ascii progress bar. So, I added a `verbose` arg to the `predict()` and `get_activation()` functions. The default values are set to `1` so that the current behavior is preserved. But if you pass in `verbose=0`, the progress bar won't display. (Which also speeds up  prediction by a small amount too.)

### CODE REVIEW

**Comment by jongwook** [comment]
Looks good to me! I'm inclined to add a command line option to suppress non-error outputs as well, but maybe for another time soon.

**Comment by justinsalamon** [comment]
@wooters thanks for the PR! I noticed it's missing updates to the functions' docstrings - I'll quickly fix that. Cheers!

**Comment by wooters** [comment]
Oh dang! I actually intended to do that.

**Comment by justinsalamon** [comment]
No worries, thanks again for your contribution!

**Pull request merged**
