### PR TITLE
Update requirements to allow tensorflow>=2.0

### PR DESCRIPTION
**Pull request by adarob**

### CODE REVIEW

**Comment by jongwook** [comment]
Thanks @adarob , I guess it means tf 2.1 soon! yay!

Out of curiosity before publishing the new package - what's the recommended workflow regarding the dependency management of the package `tensorflow-gpu` and `tensorflow`? 

Currently if I try `pip -r requirements.txt` with `tensorflow-gpu` installed, it downloads the `tensorflow` package again an installs it on top of `tensorflow-gpu`, and `tensorflow` starts to use CPU by default.

This was the reason why I didn't include either tensorflow as the pip dependency originally, but I wonder if anything changed in tf 2.0.

**Comment by adarob** [comment]
I think that with tf 2.0, there is no tensorflow-gpu anymore. They both
work under the same package.  I'm not sure how to get it to run on GPU, but
this looks promising: https://www.tensorflow.org/guide/gpu

**Comment by jongwook** [comment]
> there is no tensorflow-gpu anymore

There is a separate tensorflow-gpu 2.x package on PyPI, as seen in this from [the official install guide](https://www.tensorflow.org/install/pip?lang=python3):

image

I liked the approach of 1.15 which combined CPU and GPU in one `tensorflow` package, but then they went back to this dichotomy.

Installing both `tensorflow` and `tensorflow-gpu` makes things really annoying, and whichever installed later gets precedence - and that's why I was wondering how googlers deal with this problem.

I'd lean to removing the tensorflow dependency altogether if there isn't any better way. I can print a warning if tensorflow is not found during installation, etc.

**Comment by adarob** [comment]
Hmm, yes that is strange. I think the idea of not installing tensorflow is
a good one.

**Comment by justinsalamon** [comment]
@adarob @jongwook were you able to run a regression test to ensure the model performance doesn't change between 2.0 and 2.x > 2.0?

IIRC, the motivation for pinning it to 2.0 was to prevent unexpected model behavior, should we first add some regression tests to the existing unit tests before publishing a new release?

**Comment by jongwook** [comment]
After merging this, I haven't pushed 0.0.10 to PyPI just yet, trying to remove the tensorflow dependency again as discussed above.

While merging #40 I thought adding `tensorflow` as a dependency was fine assuming that TF 2.0 and onwards will have a unified package name (as tensorflow 1.15.0 did), but apparently they don't!

In terms of regression test (#46) we only have [a rudimentary test on sine sweep](https://github.com/marl/crepe/blob/master/tests/test_sweep.py) that would catch a catastrophic failure, but it doesn't guarantee subtle changes in performance.

**Comment by justinsalamon** [comment]
sounds like we should grab some ~100 short files of varied content and generate some regression data.

**Comment by adarob** [comment]
FYI, TF 2.1 is now available and we are unable to upgrade downstream
packages. Since you are allowing people to choose their own TF version, it
seems like the regression test is orthogonal to this change.

**Comment by jongwook** [comment]
@adarob Just pushed v0.0.10 to PyPI which does not explicitly depend on either tensorflow!

**Comment by jongwook** [comment]
[Just noticed that `tensorflow` 2.1.0 pip package supports GPU again.](https://github.com/tensorflow/tensorflow/releases/tag/v2.1.0) I support this decision personally, while it puts 2.0.0 in a weird position between 1.15.0 and 2.1.0 that both include GPU support.

We might consider adding a depenency like `tensorflow>=2.1` in the future, provided that the pip package continues to include GPU support.

**Comment by adarob** [comment]
Thanks! Oh wow, I hadn't seen that about GPU support. Very confusing...

**Pull request merged**
